Name: blockMonitorBSC.rpc
ListenOn: 127.0.0.1:18003
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: blockMonitorBSC.rpc

Postgres:
  DataSource: host=127.0.0.1 user=postgres password=ZecreyProtocolDB@123 dbname=zecreyLegend port=5432 sslmode=disable

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: myredis
    Type: node

ChainConfig:
  NetworkRPCSysConfigName: "Local_Test_Network_RPC"
  ZecreyContractAddrSysConfigName: "ZecreyLegendContract"
  StartL1BlockHeight: 800
  PendingBlocksCount: 0
  MaxHandledBlocksCount: 10000

LogConf:
  ServiceName: blockMonitorAvalanche
  Mode: console
  Path: ./log/blockMonitorAvalanche
  StackCooldownMillis: 500
