Name: blockMonitorAvalanche.rpc
ListenOn: 127.0.0.1:18003
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: blockMonitorAvalanche.rpc

Postgres:
  DataSource: host=127.0.0.1 user=postgres password=ZecreyProtocolDB@123 dbname=zecrey port=5432 sslmode=disable

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: myredis
    Type: node

ChainConfig:
  L2ChainId: 3
  NetworkRPCSysConfigName: "Local_Test_Network_RPC"
  ZecreyContractAddrSysConfigName: "Zecrey_Contract_Local"
  StartL1BlockHeight: 0
  PendingBlocksCount: 0
  MaxHandledBlocksCount: 10000

LogConf:
  ServiceName: blockMonitorAvalanche
  Mode: console
  Path: ./log/blockMonitorAvalanche
  StackCooldownMillis: 500
