apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  ports:
  - port: 8888
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  name: globalrpc-svc
  namespace: default
spec:
  ports:
  - port: 8080
  selector:
    app: globalrpc
---
apiVersion: v1
kind: Service
metadata:
  name: proverhub-svc
  namespace: default
spec:
  ports:
  - port: 38000
  selector:
    app: proverhub
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/app:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8888
        name: app
        ports:
          - name: metrics
            containerPort: 9091
          - name: app
            containerPort: 8888
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      initContainers:
      - command:
        - sh
        - -c
        - until nslookup globalrpc-svc; do echo waiting for globalrpc; sleep 2; done;
        image: busybox
        name: init-globalrpc
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockmonitor
  name: blockmonitor
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: blockmonitor
  template:
    metadata:
      labels:
        app: blockmonitor
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/blockmonitor:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: blockmonitor
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: committer
  name: committer
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: committer
  template:
    metadata:
      labels:
        app: committer
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/committer:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: committer
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: globalrpc
  name: globalrpc
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: globalrpc
  template:
    metadata:
      labels:
        app: globalrpc
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/globalrpc:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        name: globalrpc
        ports:
        - name: metrics
          containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: l2blockmonitor
  name: l2blockmonitor
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: l2blockmonitor
  template:
    metadata:
      labels:
        app: l2blockmonitor
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/l2blockmonitor:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: l2blockmonitor
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mempoolmonitor
  name: mempoolmonitor
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mempoolmonitor
  template:
    metadata:
      labels:
        app: mempoolmonitor
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/mempoolmonitor:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: mempoolmonitor
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proverclient
  name: proverclient
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: proverclient
  template:
    metadata:
      labels:
        app: proverclient
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/proverclient:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: proverclient
        resources:
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 500m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      initContainers:
      - command:
        - sh
        - -c
        - sleep 120 && until nslookup proverhub-svc; do echo waiting for proverhub;
          sleep 2; done;
        image: busybox
        name: init-proverhub
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proverhub
  name: proverhub
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: proverhub
  template:
    metadata:
      labels:
        app: proverhub
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/proverhub:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 38000
        name: proverhub
        ports:
        - name: metrics
          containerPort: 38000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 38000
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sender
  name: sender
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/sender:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: sender
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: governancemonitor
  name: governancemonitor
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: governancemonitor
  template:
    metadata:
      labels:
        app: governancemonitor
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/governancemonitor:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: governancemonitor
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-c
  name: app-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-m
  name: app-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: globalrpc-hpa-c
  name: globalrpc-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globalrpc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: globalrpc-hpa-m
  name: globalrpc-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globalrpc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: proverclient-hpa-c
  name: proverclient-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proverclient
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: proverclient-hpa-m
  name: proverclient-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proverclient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - name: prometheus
        image: "gke.gcr.io/prometheus-engine/frontend:v0.4.1-gke.0"
        args:
        - "--web.listen-address=:9090"
        - "--query.project-id=zecrey-330903"
        ports:
        - name: web
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web