apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: $NAMESPACE
spec:
  ports:
  - port: 8888
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: $NAMESPACE
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/app:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8888
        name: app
        ports:
          - name: metrics
            containerPort: 9091
          - name: app
            containerPort: 8888
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      # initContainers:
      # - command:
      #   - sh
      #   - -c
      #   - until nslookup globalrpc-svc; do echo waiting for globalrpc; sleep 2; done;
      #   image: busybox
      #   name: init-globalrpc
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-c
  name: app-hpa-c
  namespace: $NAMESPACE
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-m
  name: app-hpa-m
  namespace: $NAMESPACE
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
