---
apiVersion: v1
kind: Service
metadata:
  name: prom-frontend
  namespace: monitoring
spec:
  selector:
    app: prom-frontend
  ports:
  - name: web
    port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-frontend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-frontend
  template:
    metadata:
      labels:
        app: prom-frontend
    spec:
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - name: prom-frontend
        image: "gke.gcr.io/prometheus-engine/frontend:v0.4.1-gke.0"
        args:
        - "--web.listen-address=:9090"
        - "--query.project-id=zecrey-330903"
        ports:
        - name: web
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prom-frontend-hpa-c
  name: prom-frontend-hpa-c
  namespace: monitoring
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prom-frontend