name: autotest
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [^1.17.x]
        os: [ubuntu-latest]
        redis: [5.x]
    name: build&test
    runs-on: ${{ matrix.os }}
    steps:
      - name: check network
        run: ip addr show
      - name: login ghcr
        run: echo ${{ secrets.GH_TEST_PAT }} | docker login ghcr.io -u AI-ZJUNlict --password-stdin
      - name: ghcr image pull
        run: docker pull ${{ secrets.ZECREY_IMAGE_URI }}
      - name: image run
        run: docker run -d --name zecrey_test_image -p 3307:3306 -e MYSQL_ROOT_PASSWORD=123456 ${{ secrets.ZECREY_IMAGE_URI }} && sleep 6
      - name: docker check
        run: docker ps && docker images && sleep 10
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          redis-tls-port: "6379"
      - name: set env
        run: go env -w GOPRIVATE=github.com/zecrey-labs && git config --global url."https://${{ secrets.GH_TEST_PAT }}:x-oauth-basic@github.com/zecrey-labs".insteadOf "https://github.com/zecrey-labs"
      - name: checkcheck
        run: ps -ef | grep docker
      - name: test
        run: cd main && export dsn="${{ secrets.ZECREY_DSN }}" && make test-coverage
